"use strict";
function headerUI(){
	return '<div id="header">'
		+	'  <section id="banner">'
		+'      <div class="bg-color">'
		+'        <header id="header">'
		+'          <div class="container">'
		+'            <div id="mySidenav" class="sidenav">'
		+'              <a href="javascript:void(0)" class="closebtn" onclick="closeNav()"> &times; </a>'
		+'              <a id="login_btn">Login</a>'
		+'              <a id="add_btn">Join</a>'
        +'				<a id="board">게시판</a>'
        +'				<a id="drag_btn">드래그앤드랍</a>'
		+'            </div>'
		+'            <!-- Use any element to open the sidenav -->'
		+'            <span onclick="openNav()" class="pull-right menu-icon">☰</span>'
		+'          </div>'
		+'        </header>'
		+'        <div class="container">'
		+'          <div class="row">'
		+'            <div class="inner text-center">'
		+'              <h1 class="logo-name"> Grade Management System </h1>'
		+'              <h2>ManZZitNam</h2>'
		+'              <p>-IU-</p>'
		+'            </div>'
		+'          </div>'
		+'        </div>'
		+'      </div>'
		+'    </section>'
		+'	</div>';
}