function writerUI(){
	return '<div id="writer_box" style="width: 90%; margin:auto">'
	+'<section class="content">'
	+'<div class="row">'
	+'<div class="col-md-12">'
		+'<div class="box box-primary">'
+'<div class="box-body">'
	+'<div class="form-group">'
		+'<label for="exampleInputEmail1">작성자</label> '
		+'<div type="text"'
			+'id="writer" class="form-control" placeholder="Enter Writer" />'
	+'</div>'
	+'<div class="form-group">'
		+'<label for="exampleInputEmail1">제목</label> '
		+'<input type="text" id="title" class="form-control" placeholder="Enter Title">'
	+'</div>'
	+'<div class="form-group">'
		+'<label for="exampleInputPassword1">내용</label>'
		+'<textarea class="form-control" id="ctn" rows="3"'
			+'placeholder="Enter ..."></textarea>'
	+'</div>'
+'</div>'
		+'</div>'
	+'</div>'
+'</div>'
+'</section>'
+'</div>';
}